version: 0.2

env:
  variables:
    BUILD_TYPE: "test"

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase... `pwd`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - touch test.bin
  post_build:
    commands:
      - echo Build completed on `ls -l`
artifacts:
  files:
    - test.bin
  discard-paths: yes