version: 0.2
phases:
  build:
    commands:
      - cd /usr/src/app 
      - /usr/local/bin/carton exec pp $CODEBUILD_SRC_DIR/src/msrn.pl -o $CODEBUILD_SRC_DIR/src/msrn.bin
artifacts:
  files:
    - '**/*'
  base-directory: src
  discard-paths: no
  