version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase... `echo $PWD`
      - apt-get update
      - apt-get install -y docker
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - cd src&&pwd
  build:
    commands:
      - echo Build started on `date`
      - docker run -v $PWD/bin:/usr/src/app/bin --name msrn-dev msrn-dev
  post_build:
    commands:
      - echo Build completed on `ls`
artifacts:
  files:
    - bin/msrn.bin
  discard-paths: yes